image:
  file: ./dev/gitpod.dockerfile

ports:
  - port: 8085
    onOpen: open-browser

tasks:
  - name: Terminal
    init: bash ./dev/createDevEnv.sh
  - name: nginx
    command: nginx && multitail /var/log/nginx/access.log -I /var/log/nginx/error.log
