image:
  file: ./docker/gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-browser

tasks:
  - init: bash ./docker/createDevEnv.sh
    command: nginx && multitail /var/log/nginx/access.log -I /var/log/nginx/error.log
