version: '3'

services:
  obj2dev:
    image: docker.pkg.github.com/kaisalmen/three-wtm/devbox:latest
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    volumes:
      - ./:/home/obj2/workspace/:rw
    command: ["bash", "-c", ". /home/devbox/.local/bin/env/configureN.sh && npm install && npm run dev"]
    working_dir: /home/obj2/workspace
    container_name: obj2dev
