version: '3'

services:
  obj2dev:
    image: obj2dev
    build:
      dockerfile: dev/Dockerfile
      context: .
    ports:
      - 8085:8085
    volumes:
      - ./:/workspace/WWOBJLoader/:rw
    command: ["bash", "/workspace/WWOBJLoader/dev/runDevEnv.sh"]
    container_name: obj2dev
