version: '3'

services:
  obj2dev:
    image: obj2dev
    build:
      dockerfile: dev/Dockerfile
      context: .
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    volumes:
      - ./:/workspace/WWOBJLoader/:rw
    command: ["bash", "/workspace/WWOBJLoader/dev/runDevEnv.sh"]
    container_name: obj2dev
