version: '3'

services:
  obj2dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    volumes:
      - ./:/home/devbox/workspace/:rw
    command: ["bash", "-c", "npm install && npm run build && npm run dev"]
    working_dir: /home/devbox/workspace
    container_name: obj2dev
