version: '3'

services:
  obj2dev:
    image: obj2dev
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 8085:80
    volumes:
      - ./:/project/:rw
    command: ["bash", "/project/docker/runDevEnv.sh"]
    container_name: obj2dev
