version: '3'

services:
  obj2dev:
    image: obj2dev
    build:
      dockerfile: dev/Dockerfile
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./:/home/obj2/workspace/:rw
    command: ["bash", "-c", ". /home/obj2/.local/bin/env/configureN.sh && npm install && npm run dev"]
    working_dir: /home/obj2/workspace
    container_name: obj2dev
